### ISSUE TITLE
Mac version: no pointer ?

### ISSUE THREAD

**Issue by karawitan** [jpca/ld50_avoidinevitable#4]
Hello @jpca !

  I just tried the Mac version, display is working fine, sound also (very nice btw), but I don't know how to move. Tried with both the mouse and the magic keypad, but no pointer appear on the screen.

   So the inevitable happens, the ice melt, and I take a very very cold bath. I'd like to explore the North Pole ! please make pointer work on mac :)

**Comment by jpca** [comment]
you need to use WASD or ZQSD key and space to jump ! have fun

**Comment by karawitan** [comment]
Ok working great !
